server:
 port: 54321
 
# DataSource settings: set here your own configurations for the database 
# connection. In this example we have "netgloo_blog" as database name and 
# "root" as username and password.
spring: 
 datasource: 
  url: jdbc:mysql://localhost:3306/zh_core
  username: root
  password: root
  # Keep the connection alive if idle for a long time (needed in production)
  testWhileIdle: true
  validationQuery: SELECT 1
 # Show or not log for each sql query
 jpa: 
  show-sql: true
  hibernate:
   # Hibernate ddl auto (create, create-drop, update) 
   #ddl-auto: update
   naming-strategy: org.hibernate.cfg.DefaultNamingStrategy
   # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
   # stripped before adding them to the entity manager)   
   properties:
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    hibernate:
     dialect: org.hibernate.dialect.MySQL5Dialect     
 ### i18n setting.
 ########################################################
 #指定message的basename，多个以逗号分隔，如果不加包名的话，默认从classpath路径开始，默认: messages 
 messages: 
  basename: i18n/messages,zh/framework/validator/ValidationMessages_zh_CN
  #设定加载的资源文件缓存失效时间，-1的话为永不过期，默认为-1
  cache-seconds: 3600